Add deployment rolling updates when fe or be changes during the main branch update

diff --git a/.github/workflows/sw-fe-docker-publish.yml b/.github/workflows/sw-fe-docker-publish.yml
--- a/.github/workflows/sw-fe-docker-publish.yml
+++ b/.github/workflows/sw-fe-docker-publish.yml
@@ -318,9 +318,36 @@ jobs:
               body: `🚀 SW-FE Docker image published for testing!\n\n**Image Name:** \`${process.env.REGISTRY}/${process.env.IMAGE_NAME_LOWERCASE}:pr-${context.issue.number}\``
             })
 
+  rollout-dev:
+    name: Rollout Dev
+    needs: [check-paths, check-image, merge]
+    if: |
+      always() &&
+      needs.check-paths.outputs.fe == 'true' &&
+      github.event_name == 'push' &&
+      github.ref == 'refs/heads/main' &&
+      (needs.check-image.outputs.exists == 'true' || needs.merge.result == 'success')
+    runs-on: polecatworks-runner
+    steps:
+      - name: Set up kubectl
+        uses: azure/setup-kubectl@v4
+        with:
+          version: "latest"
+
+      - name: Configure Kubeconfig
+        run: |
+          kubectl config set-cluster local --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+          kubectl config set-credentials runner --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+          kubectl config set-context local --cluster=local --user=runner
+          kubectl config use-context local
+
+      - name: Trigger Rolling Restart
+        run: |
+          kubectl rollout restart deployment/sward-warden-fe-nginx-view -n sward-warden-dev
+
   ci-success:
     name: SW-FE CI Success
-    needs: [ check-paths, check-image, merge ]
+    needs: [ check-paths, check-image, merge, rollout-dev ]
     if: always() && github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     steps:
@@ -329,6 +356,10 @@ jobs:
           if [[ "${{ needs.check-paths.outputs.fe }}" == 'true' ]]; then
             if [[ "${{ needs.check-image.outputs.exists }}" != 'true' && "${{ needs.merge.result }}" != 'success' ]]; then
                echo "Build/Merge failed!"
+               exit 1
+            fi
+            if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" && "${{ needs.rollout-dev.result }}" != 'success' ]]; then
+               echo "Rollout failed!"
                exit 1
             fi
           fi
